### ISSUE TITLE
video tutorial

### ISSUE THREAD

**Issue by JunMa11** [wiesenfa/challengeR#1]
Dear @wiesenfa ,

Thanks for sharing the excellent tool. 
I have read your paper just know. This tool seems super useful.

However, this tool is based on R. I'm a python user and know nothing about R.
So it's a little hard for me to use this tool based on the `readme` file.

**Would it be possible for you to provide a video tutorial about how to use this tool?**

Looking forward to your reply.

Kindest regards,
Jun

**Comment by JunMa11** [comment]
Unsuccessful R explore tour.

I install R and Rstudio. Then I make a new script and copy the demo code.
![image](https://user-images.githubusercontent.com/19947331/67622376-2268b080-f84c-11e9-841f-e6c501af84d9.png)
![image](https://user-images.githubusercontent.com/19947331/67622393-49bf7d80-f84c-11e9-8d5a-5d33097ba8c0.png)

However, when I run the code, the **following error** occurred.

![image](https://user-images.githubusercontent.com/19947331/67622527-76c06000-f84d-11e9-9095-f063b1fabd7e.png)
![image](https://user-images.githubusercontent.com/19947331/67622540-a5d6d180-f84d-11e9-9732-0cc192ac321b.png)
![final](https://user-images.githubusercontent.com/19947331/67622551-b2f3c080-f84d-11e9-814d-a86e532850da.png)

Q1: **Could you share your insight on this error?**

Q2: What the **exact data format of the  `assessment_data.csv` file** in the single-task and the multi-task setting?
For example, the single-task  `assessment_data.csv`  is

![image](https://user-images.githubusercontent.com/19947331/67622693-28ac5c00-f84f-11e9-9806-168935498275.png)
Is this right?

If I want to add a new task (multi-task setting), do I need to add a new sheet in `assessment_data.csv`  or something else?

![image](https://user-images.githubusercontent.com/19947331/67622723-74f79c00-f84f-11e9-9b81-b0ca11b3821a.png)

Adding an `assessment_data.csv` as example would be highly appreciated.

Best regards,
Jun

**Comment by wiesenfa** [comment]
Q1: Please refer to the updated Readme. The "Warning message" you encounter (it is a warning not an error), will not affect challengeR.

Q2: There is no such thing as multiple sheets in csv file format (you are probably referring to xlsx format). There is now an example in the Readme in addition to the text explanation. You can also take a look at the simulated data in object "data_matrix" to see how a data set may look like.

Hope this helps!

**Comment by JunMa11** [comment]
Hi @wiesenfa ,

Thanks for your help very much.

Q1: Follow the guidance,
> If you are asked whether you want to update installed packages and you type “a” for all, you might need administrator rights to update R core packages. You can also try to type “n” for updating no packages.

> library(challengeR)

I still can't load the `challengeR` package. **The error shows no challengeR.** However, I indeed put the `challengeR` folder into the current directory (the red arrow).

![image](https://user-images.githubusercontent.com/19947331/67734459-1cd1bd00-fa3c-11e9-9819-ddc375cda669.png)


Q2: Would it be possible for you to add the `data_matrix.csv` (corresponding  to the simulated data in object "data_matrix") file into this `respo`.
Sorry for the rude request.

I really appreciate your kind help.

Best regards,
Jun

**Comment by wiesenfa** [comment]
Please run each code line step by step. As you can see in your screenshot the essential code line
devtools::install_github("wiesenfa/challengeR", dependencies = TRUE)
was inserted when a response to "Update all/some/none" was expected.

Q2: I'll consider adding the csv although I do not really get the point to be honest.

Hope this helps!

**Comment by JunMa11** [comment]
@wiesenfa It works now. Thank you so much. Really a great tool.

@niklr That is what I thought :). Thank you.

**Comment by wiesenfa** [comment]
Thanks. csv now added to the repos.
