### ISSUE TITLE
question on bootstrap

### ISSUE THREAD

**Issue by JunMa11** [wiesenfa/challengeR#2]
![image](https://user-images.githubusercontent.com/19947331/67621360-e4ff2580-f841-11e9-9eb6-11012df7bfc2.png)

For the bootstrap sample, does the highlight sentence mean random sampling n cases from n test cases?
If yes, it's a little weird,  because each sampling will be the same (sampling the whole test set) in this way.

**Comment by wiesenfa** [comment]
Dear JunMa11,
this is a standard original nonparametric bootstrap. So test cases are drawn _with replacement_.
E.g. if a test set consists of 4 test cases A B C D. One bootstrap sample could be A A B D, another one A B B C, another one B C C C, etc. That is, each test case can appear multiple times.

**Comment by JunMa11** [comment]
Got it. Thanks for your answer very much.
