### ISSUE TITLE
Define list of visualizations generated in report as parameter

### ISSUE THREAD

**Issue by niklr** [wiesenfa/challengeR#3]
Dear @wiesenfa 
Is it possible to define a list of visualizations that are generated and included in the PDF report as parameter? For example, I might be interested in just the dot- and boxplots, significance maps and heatmaps. In this case it would be nice to just pass those 3 visualization identifiers and get a reduced PDF report as result.
Best regards,
Roman Niklaus

**Comment by wiesenfa** [comment]
Dear @niklr 
there will be probably next week an update the possibility to generate reports excluding anything related to bootstrapping.
You can also produce plots directly without report, although syntax is a bit inconsistent yet. I'll give you more details on that as soon as this is improved.

Best,
Manuel

**Comment by wiesenfa** [comment]
report can now also exclude bootstrap results (version 0.2.0
