### ISSUE TITLE
how to create these figures?

### ISSUE THREAD

**Issue by JunMa11** [wiesenfa/challengeR#30]
Dear @wiesenfa ,

I found the two great figures in this [paper](https://arxiv.org/abs/1904.08128v2) that used `challengeR`.

Do you know what tools in challengeR can be used to create the figures?

![Figure1](https://user-images.githubusercontent.com/19947331/78450046-60e18180-76ae-11ea-9a80-9294aca66c88.png)

![Figure2](https://user-images.githubusercontent.com/19947331/78450050-6c34ad00-76ae-11ea-9d7e-97009965a9eb.png)

Best regards,
Jun

**Comment by wiesenfa** [comment]
Dear @JunMa11 ,
this are custom made functions by the authors. A related plot to the first is given in multi task (considering the method variations as tasks) rankings, but stacking the bars; blob plots there also provide the same information. We may consider inclusion of such a visualization in the future. 
The second and third plots are not so much concerned with general validations and are not in the scope of the package.
