### ISSUE TITLE
Error in loadNamespace(name) : there is no package called ‘devtools’

### ISSUE THREAD

**Issue by eceisik** [wiesenfa/challengeR#33]
Dear @wiesenfa,
 While installing packages I got the below error.  I am not very familiar with R. Could you please help me?

```
if (!requireNamespace("devtools", quietly = TRUE)) install.packages("devtools")
if (!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager")
BiocManager::install("Rgraphviz", dependencies = TRUE)
devtools::install_github("wiesenfa/challengeR", dependencies = TRUE)

```
> devtools::install_github("wiesenfa/challengeR", dependencies = TRUE)
Error in loadNamespace(name) : there is no package called ‘devtools’

Best,
Ece

**Comment by wiesenfa** [comment]
Dear @eceisik,
did all code which comes before ran smoothly, in particular what does
> install.packages("devtools")

give? This ist where library "devtools" is installed which seems to be missing.

Cheers,
Manuel

**Comment by eceisik** [comment]
Dear @wiesenfa,

 I changed the first line as below and the problem was solved. Thank you for your fast reply.

`if (!requireNamespace("devtools", quietly = TRUE)) install.packages("devtools", ,type="win.binary")`
