### ISSUE TITLE
plot

### ISSUE THREAD

**Issue by gc-js** [wiesenfa/challengeR#37]
I need to plot the following fig by myself, how do I extract the data out?
![image](https://github.com/wiesenfa/challengeR/assets/55502012/7813e1fd-c920-4cca-8214-bf4f2cf84db4)

**Comment by wiesenfa** [comment]
if you run 

```
kendall <- kendall.bootstrap.list(ranking_bootstrapped)
```

you'll get a list object with Kendall's tau for each bootstrap sample. From this you can compute quantiles etc.
to obtain a vector for a single task (say "task1") then use

```
kendall$task1
```

hope this helps
