### ISSUE TITLE
clang: error: unsupported option '-fopenmp'

### ISSUE THREAD

**Issue by YaoZhang93** [wiesenfa/challengeR#39]
Hi Manuel,

I am trying to install challengeR on macOS 10.15. When I followed the installation instruction and ran this cmd "BiocManager::install("Rgraphviz", dependencies = TRUE)", I got this error. I asked chatGPT, but it still did not work. Would you happen to have any idea what is going on here?

The detailed error message is as follows:

installing the source package ‘mgcv’

trying URL 'https://cran.rstudio.com/src/contrib/mgcv_1.9-0.tar.gz'
Content type 'application/x-gzip' length 1112050 bytes (1.1 MB)
==================================================
downloaded 1.1 MB

* installing *source* package ‘mgcv’ ...
** package ‘mgcv’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include -fopenmp -fPIC  -Wall -g -O2  -c coxph.c -o coxph.o
clang: error: unsupported option '-fopenmp'
make: *** [coxph.o] Error 1
ERROR: compilation failed for package ‘mgcv’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/mgcv’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/mgcv’

The downloaded source packages are in
	‘/private/var/folders/6r/k1_bjsls4n15b1jpy7j5591m0000gn/T/RtmpGHf18P/downloaded_packages’
Warning messages:
1: package(s) not installed when version(s) same as or greater than current; use `force = TRUE` to
  re-install: 'Rgraphviz' 
2: In install.packages(update[instlib == l, "Package"], l, repos = repos,  :
  installation of package ‘mgcv’ had non-zero exit status

**Comment by wiesenfa** [comment]
I am confused why it is installing from source. Have you been asked "Do you want to install from sources the package which needs compilation?". If yes, you should type "n" for no. Then precompiled version is installed. otherwise please try
```
install.packages("mgcv")
```

before installing Rgraphviz

**Comment by YaoZhang93** [comment]
I see. It installed from the source since It 
"unable to access index for repository https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6:
cannot open URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/PACKAGES"
Thanks for your help.
