### ISSUE TITLE
Reduce visualization in report to top n algorithms

### ISSUE THREAD

**Issue by niklr** [wiesenfa/challengeR#5]
Dear @wiesenfa 
As pointed out in the paper, visualization methods often reach their limit when the number of algorithms are too large.
![grafik](https://user-images.githubusercontent.com/4712166/67938996-eaa59400-fbd0-11e9-97d5-b4f366f15d48.png)
Is it already possible with the current implementation to reduce the visualization to a top list of algorithms displayed in the report (e.g. by specifying a parameter topN=10)?
Best regards,
Roman Niklaus

**Comment by wiesenfa** [comment]
No unfortunately not yet. I put it on the feature list as this is very important. Note that running the report as it is now with a reduced number of algorithms will underestimate the uncertainty in the rankings.
Please give me some time to implement it (I am at the moment doing everything on my own, so if you want to contribute you are more than welcome).

Best regards,
Manuel

**Comment by JunMa11** [comment]
Dear @wiesenfa ,

Are there any updates on the new features?

Best regards,
Jun

**Comment by wiesenfa** [comment]
Dear @JunMa11 

new update now supports reduction of algorithms in single task case. Though not thoroughly tested yet (and documentation scarce). See change log in readme.

Hope this is useful.
Best,
Manuel
